version: "3"

services:
  backend:
    container_name: Backend
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
    command: npm run start   
    networks: 
      - homelike_network 
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: homelike
      POSTGRES_USER: homelike_user
      POSTGRES_PASSWORD: homelike_password
    networks:
      - homelike_network
networks:
  homelike_network: